// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	UserID    uuid.UUID
	Username  string
	HashedPw  string
	Admin     bool
	CreatedAt time.Time
	UpdatedAt time.Time
}
